[project]
name = "data-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "helper-functions-ea",
    "matplotlib>=3.10.3",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "plotly>=6.1.0",
    "quantlib>=1.38",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.4",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.4.2",
]

[tool.uv.sources]
helper-functions-ea = { git = "https://github.com/energyaspects/helper_functions.git", rev = "latest" }
